Feature update for capitec merchant acquiring project
electrumpayments/qr-payment-service-interface pull request #11
Opened 2021-04-08 08:30 UTC by PatrickColborne

* Added a new model object called `QrProperties`.
* Added the following member variables to the `CreateQrCodeRequest` and `CreateQrCodeResponse` model objects:
    * `customer`
    * `qrProperties`
* Removed the following dependencies which are brought in by `service-interface-base`:
    * `joda-time`
    * `swagger-jersey2-jaxrs`
    * `swagger-hibernate-validations`
    * `jersey-server`
    * `jersey-common`
    * `jersey-container-servlet`
    * `jersey-client`
    * `jersey-media-json-jackson`
    * `hibernate-validator`
* Added minimum requirement for `service-interface-base` v3.30.0 and up.

There appears to be an issue with Hugo on Circle Ci but I can't figure out how to fix it so I am leaving it for now.

2021-04-15 14:50 UTC, mattsegers requested changes

2021-04-15 14:50 UTC, mattsegers commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private Boolean singleUse = null;
I think we need to add some reasonable pattern matching to some of these? expiry date should probably conform as per other dates. Maybe that's the only one...

Having said that, should it be a `Date` object? Should it perhaps not be of the Java8 family of time utils?

2021-04-30 09:38 UTC, PatrickColborne commented on pom.xml
> +          <detectJavaApiLink>false</detectJavaApiLink>
Aaaah! I was getting these weird Java Docs errors that were preventing me from building successfully. This was the suggested solution on Stack Overflow. The error I was getting looked like this:
```
[WARNING] javadoc: warning - Error fetching URL: https://selenium.googlecode.com/git/docs/api/java
```

2021-04-30 09:46 UTC, PatrickColborne commented on release-notes.md
> +    * `hibernate-validator`
I changed it to this:
```
* The `service-interface-base` provides a lot of dependencies that it previously didn't. For this reason the following
  dependencies were removed from this project's pom file:
    * `joda-time`
    * `swagger-jersey2-jaxrs`
    * `swagger-hibernate-validations`
    * `jersey-server`
    * `jersey-common`
    * `jersey-container-servlet`
    * `jersey-client`
    * `jersey-media-json-jackson`
    * `hibernate-validator`
```

I hope that that's better?

2021-04-30 09:48 UTC, PatrickColborne commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +   @ApiModelProperty(required = false/*TODO: true or false?*/, value = "A collection of attributes that describe how a QR code is intended to be used for transacting.")
😎Aaah! Smart man. I've checked and it is true so I have updated it.

2021-04-30 09:53 UTC, PatrickColborne commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private Boolean singleUse = null;
It looks as though Sara has updated the QR manager API to use `OffsetDateTime` rather than `Date` so I will update this too.

2021-04-30 12:31 UTC, mattsegers approved these changes

2021-04-30 13:12 UTC, mattsegers approved these changes

2021-04-30 13:12 UTC, mattsegers commented on pom.xml
> +          <detectJavaApiLink>false</detectJavaApiLink>
As discussed, rather fix the javadoc issues - after they gucci so approved

2021-05-03 09:11 UTC, PatrickColborne commented
Tried fixing the Java docs issue without `<detectJavaApiLink>false</detectJavaApiLink>` but couldn't manage.

2021-05-03 09:26 UTC, merged