Fix the qr parameters object which contains a guid rather than a UUID
electrumpayments/qr-payment-service-interface pull request #15
Opened 2021-05-26 12:36 UTC by PatrickColborne

2021-05-27 09:00 UTC, CaseyODonnell92 requested changes
I'm pretty sure this is all good. Just one small doc change. Let's only actually release and deprecate the old version when we really need to and are a bit more confident.

2021-05-27 16:32 UTC, CaseyODonnell92 approved these changes
Just a reminder to update release notes and pom

2021-06-18 12:43 UTC, CaseyODonnell92 requested changes

2021-06-18 12:43 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
>     private Boolean singleUse = null;
This field has recently been removed - feeling thankful that we waited! Please drop this guy.

2021-06-18 14:38 UTC, CaseyODonnell92 requested changes

2021-06-18 14:38 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
>              && Objects.equals(this.overPaymentAllowed, qrProperties.overPaymentAllowed)
Can't seem to comment on where the field is actually defined.
Please remove `overPaymentAllowed`. The reason for this is that it intersects somewhat with how we will have to support tip amount specification later on and we aren't confident regarding what that will look like. So if we remove it now, we can always add it back at a later stage and that change won't be considered breaking.

2021-06-21 06:46 UTC, CaseyODonnell92 approved these changes

2021-06-21 06:46 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
>      *
On the line above this, please align the Javadac with the Swagger description. Sorry I didn't catch this last time!

2021-06-21 07:14 UTC, TimElectrum requested changes

2021-06-21 07:14 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
>     private LedgerAmount value = null;
I think we should remove this field - there's already an `amounts` field next to the `qrProperties` in requests

2021-06-21 07:40 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
The current state of the management API is such that no account IDs are present in the assign QR request. Maybe that needs to change?

2021-06-25 11:44 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
ja, it probably does. Specifying a destination account is similar to specifying a merchant in that both identify the recipient of the payment. (In our world, at the moment, it's presumed that the owner of the QR code is meant to be who is receiving the payment.)

The info needed to request a QR is split into 2 broad groups:

1. _who_ the QR code is for i.e. the `Owner`
2. _how_ the transaction should occur i.e. the `QrProperties`

The destination account is very much part of the "who", not the "how"

2021-06-25 11:52 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
Cool, so we can easily add an account ID on Owner. We just need to add a sensible field to `CreateQrCodeRequest` to capture it at request time. And obviously it shouldn't be in `QrProperties`

2021-06-25 11:54 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
Presumably, this also means we should take the destinationAccountId out the `QrParameters` in the management API.

2021-06-28 09:21 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
> Presumably, this also means we should take the destinationAccountId out the QrParameters in the management API.

Yip

2021-06-28 09:21 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
> Cool, so we can easily add an account ID on Owner. We just need to add a sensible field to `CreateQrCodeRequest` to capture it at request time. And obviously it shouldn't be in `QrProperties`

I wonder if we should add `PaymentMethods` to `CreateQrCodeRequest`. The intention would be "give me a QR which can be used for this `PaymentMethod`". I think that's clear and sensible enough but it kinda goes against the design of _this_ API. If a particular `PaymentMethod` was going to be used it would only become apparent in the subsequent `PaymentRequest` so making it appear in the request for a QR code seems a little unnecessary (an example of a lack of temporal decomposition?)

But, I don't think adding `PaymentMethod` to the `CreateQrCodeRequest` actually _inhibits_ the original intention of the API (making tran details appear to everyone in the `PaymentRequest`). And with our possible intention to make the `ScanNotification` response include more transaction details, I think it would be okay to add a `PaymentMethod` to the `CreateQrCodeRequest`

2021-07-02 11:45 UTC, CaseyODonnell92 requested changes
Just some really small suggestions around wording in the documentation.

2021-07-02 11:45 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
>      * @since 1.5.0
```suggestion
    * @since 1.8.0
```

2021-07-02 11:45 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +    *           instance
```suggestion
    * @param qrProperties
    *           the collection of attributes that describe how the requested QR code is intended to be used for 
    *           transacting.

```

2021-07-02 11:45 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +   @ApiModelProperty(value = "")
```suggestion
   @ApiModelProperty(value = "A list of payment methods with which the QR owner will accept payment. The paymentMethods"
           + " specify the destination to which funds may be transferred when the QR code is scanned.")
```

2021-07-02 11:45 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +    * A list of payment methods that the QR owner will accept payment with. The paymentMethods specify the destination
```suggestion
    * A list of payment methods with which the QR owner will accept payment. The paymentMethods specify the destination
```

2021-07-02 11:50 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +   protected List<PaymentMethod> paymentMethods = new ArrayList<>();
Is there some specific reason that you opted for a list here? It kind of makes sense to me that you might be able to have more than one payment method discoverable via the QR code. The only hassle I foresee is that we will just have to keep this API aligned with the QR Manager. So if we have multiple methods available here, we should _probably_ facilitate storing that info in the QR Manager.

2021-07-07 13:03 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +   private String destinationAccountId = null;
beefy conversation I don't want to resolve because I don't want it to become hidden. But happy to consider it resolved.

2021-07-07 13:13 UTC, TimElectrum requested changes
A nice project to demonstrate the importance of good tests 🙈 

The existing tests are poor in that they just use empty objects to test the broiler plate methods (there was an issue previously around "identical" instances of objects having different hash codes etc.)

If the tests used _real_ data including some of the fields you're removing then they would have started failing and it would have highlighted the breaking nature of your changes...

So there are two things we need to address (neither of which is your fault but you're working this now so...):

1. Please add some "new model" tests which test using more sensible data than the empty objects used at the moment. You can extend the class in the base API's testing package like we do with our other APIs. Please keep the "empty object" tests though - they're highlighting an important thing.
2. We need to think about how to handle these breaking changes - ideally we don't want to release a new major version or make breaking changes because that has knock-on effects elsewhere.

2021-07-07 13:13 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> -   private Boolean overPaymentAllowed = null;
I think we can keep this. This is separate to a tip and adding support for a tip doesn't negate the need for this field

2021-07-07 13:13 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +    * A short description for the QR code defining why it was created.
it might be worth adding that this is intended to be displayed to the person scanning the QR code to provide them with context for the QR

2021-07-07 13:15 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
>              && Objects.equals(this.overPaymentAllowed, qrProperties.overPaymentAllowed)
1. Removing it now _is_ a breaking change and I don't think it makes sense to "remove it now because we can add it later as a non-breaking change".
2. "Over payment allowed or not" is a different question to "tip allowed or not". Think about bill payments and policy payments - sometimes an overpayment is allowed and sometimes it's not. But you'd never think about tipping!

I think `overPaymentAllowed` should stay

2021-07-07 13:16 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +   protected List<PaymentMethod> paymentMethods = new ArrayList<>();
yeah, I agree.

Is it a hassle to update QR Manager as you described?

2021-07-15 14:46 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeMessage.java
> +   protected List<PaymentMethod> paymentMethods = new ArrayList<>();
I don't know exactly what it ought to look like just yet... Might just be in the form of multiple owner accounts? (i.e. you can pay me at one of these accounts after scanning my QR). At any rate, we know it makes sense here, so we will make it work in QR Manager one way or another.

2021-07-20 09:48 UTC, CaseyODonnell92 requested changes
Please re-add the test class you removed. It's still valuable and if you have a look at Tim's comment, you'll see he still wanted it to hang around. Tests look good! Just gotta add some missing fields to make these tests really sensitive to unintended changes.

2021-07-20 09:48 UTC, CaseyODonnell92 commented on src/test/java/io/electrum/qr/api/model/NewModelTest.java
> +                  .errorType(ErrorDetail.ErrorType.UPSTREAM_UNAVAILABLE);
```suggestion
            new ErrorDetail().id("c01cafdb-6ecc-4612-8acf-2d8dfd04a624")
                  .originalId("b46f7ddb-c73c-496c-8849-2a3396aac861")
                      .errorType(ErrorDetail.ErrorType.UPSTREAM_UNAVAILABLE)
                      .errorMessage("Issuer Unavailable")
                      .detailMessage("This is a long explanation of why this message failed.")
                      .providerErrorCode("ProvideError")
                      .providerErrorMsg("Provider error message: we experienced a server error")
                      .providerRef("abcdef1234")
                      .tranId("V337HvR6TLWy+URFFLWE4g");
```
If I'm not mistaken, the goal of these tests is to detect any problems with changes to any of the model definitions that are unintentionally breaking. I think that we accomplish that better if we cover all of the top-level fields of every model definition.

2021-07-20 09:48 UTC, CaseyODonnell92 commented on src/test/java/io/electrum/qr/api/model/NewModelTest.java
> +                  .amounts(new Amounts().requestAmount(new LedgerAmount().amount(12189L).currency("710")))
```suggestion
            new PaymentRequest().tranId("V337HvR6TLWy+URFFLWE4g")
                  .partner(new Institution().id("0027").name("Masterpass"))
                  .partnerPaymentToken("6731210090")
                  .amounts(new Amounts().requestAmount(new LedgerAmount().amount(12189L).currency("710")))
```

2021-07-20 09:48 UTC, CaseyODonnell92 commented on src/test/java/io/electrum/qr/api/model/NewModelTest.java
> +            new PaymentReversal().tranId("LKdTE6nCQlyrqmQe5ZhczQ")
```suggestion
            new PaymentReversal().tranId("LKdTE6nCQlyrqmQe5ZhczQ")
                              .partner(new Institution().id("0027").name("Masterpass"))

```

2021-07-20 09:48 UTC, CaseyODonnell92 commented on src/test/java/io/electrum/qr/api/model/NewModelTest.java
> +                  .thirdPartyIdentifiers(Arrays.asList());
If we leave this empty and someone were to change the type of this field from `List<ThirdPartyIdentifier>` to any other kind of list, this test wouldn't pick that up. So we need at least one of those in there.

2021-07-20 18:06 UTC, CaseyODonnell92 requested changes
Just a little worried about the toString/equals changes. Otherwise we're done!

2021-07-20 18:06 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/CreateQrCodeRequest.java
> +      StringBuilder sb = new StringBuilder("class CreateQrCodeRequest {").append(System.lineSeparator());
All of the other `toString` have this pattern: print the child class fields within one set of curly braces, and then print the result of `super.toString()` after that. Is there a reason you changed this specific class's implementation? If not, no need for changes.

2021-07-20 18:06 UTC, CaseyODonnell92 commented on src/test/java/io/electrum/qr/api/model/ModelsTest.java
> +package io.electrum.qr.api.model;
I think you put this file back in a different package. Probably not a problem?

2021-07-21 14:07 UTC, merged