Feature: Notification recipients
electrumpayments/qr-payment-service-interface pull request #19
Opened 2021-08-06 12:42 UTC by CaseyODonnell92

2021-08-06 12:50 UTC, TimElectrum requested changes
just the util `toIndentedString` method

2021-08-06 12:50 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/NotificationParameters.java
> +   }
I think there's a `public static` version of this in the base API so that we don't need to redefine it in each class

2021-08-06 12:50 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/NotificationRecipient.java
> +   }
again, I think there's a util version of this

2021-08-06 12:50 UTC, TimElectrum commented on pom.xml
> +  <version>${major-version}.${minor-version}.${patch-version}-RC1</version>
obligatory RC reminder

2021-08-10 07:42 UTC, TimElectrum requested changes

2021-08-10 07:42 UTC, TimElectrum commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +      sb.append("    notificationParameters: ").append(toIndentedString(notificationParameters)).append("\n");
oh, you can also remove these `toIndentedString` methods. In fact, do you mind going through all the models and switching to the one in the base API?

2021-08-10 07:42 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> -Released 4 August 2021
is there a reason you removed the previous release date?

2021-08-10 07:43 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +      sb.append("    notificationParameters: ").append(toIndentedString(notificationParameters)).append("\n");
No problem, on it

2021-08-10 07:44 UTC, CaseyODonnell92 commented on src/docs/devguide/hugo/site/content/release-notes.md
> -Released 4 August 2021
Thanks for catching this, no idea how that happened

2021-08-10 07:51 UTC, CaseyODonnell92 commented on src/main/java/io/electrum/qr/api/model/QrProperties.java
> +      sb.append("    notificationParameters: ").append(toIndentedString(notificationParameters)).append("\n");
Looks like this is the only class that was making use of its own `toIndentedString` (I just did a search on the method name).

2021-08-10 08:12 UTC, TimElectrum approved these changes

2021-08-10 08:21 UTC, merged